### PR TITLE
Update paper.md

### PR DESCRIPTION
**Pull request by vbhoyar**

### CODE REVIEW

**Comment by IzoldaIU** [comment]
Hey Vishal, I am getting a message that this branch has conflicts that must be resolved. Can you "git pull" to make sure you have the latest updates on your local machine and then push your changes? Last night I made a few changes while we were talking and I am not sure if they are included in your version of the file. The "merge pull request" button is grayed out for me right now. Thanks!

**Comment by laszewsk** [comment]
please also see my comments

**Comment by laszewsk** [comment]
I fixed the conflicts and merged

**Comment by laszewsk** [comment]
you need to do a pull

**Pull request merged**
